# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d54b02f19a1872acb21d69a65863bff1d65106684deb2b3e2c0c374b447d0c47763be46c4b35da40eb8533e2e9d797aa7f48ed13d0eb2a9361bad71b15b344a

test:
  secret_key_base: 10ec0a28702637ba7678b13fba3e81bd1b5b371dad9cbb394b0038ef0c8d4c9ceeb58f3093dca45860bceb6dddf876c7ca562da604a419b2970e44acc1b77ea7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
